### ISSUE TITLE
0.2.1 fails to install with ember install with ember-cli 1.13.8

### ISSUE THREAD

**Issue by cigoe** [lifegadget/ui-selectize#13]
Steps to reproduce
1. `ember init` a new project
2. `ember install ui-selectize` to install this addon and the error below is thrown

> The package `ui-selectize` is not a properly formatted package, we have used a fallback lookup to resolve it at `/tmp/test/node_modules/ui-selectize`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
> 
> The `ui-selectize` addon could not be found at `/tmp/test/node_modules/ui-selectize`.

Attempting to start the server will also throw the above message. Quick fix is to downgrade to 0.1.6 in package.json and add selectize to the bower.json file manually and then the server boots

**Comment by yankeeinlondon** [comment]
I think this came into existence as a result of earlier versions NOT actually installing the dependency with the bower "selectize" module. Obviously I attempted to fix that and broke something else. I'll look at it now. The good news is that even though you got the error message I'm pretty sure it _did_ install itself and if you just do a `npm install` it will install without complaint (because it's not trying to do the bower steps above).

**Comment by yankeeinlondon** [comment]
try `0.2.3` it should not give the error but I think it is still failing to automatically install the bower dependency on **selectize** but as you already have that it should work ok for you. I'll leave this open for now as the problem isn't fully solved

**Comment by validkeys** [comment]
I am getting this error on a fresh install (ember new app...) (after manually installing selectize)

![screen shot 2015-10-15 at 8 18 36 am](https://cloud.githubusercontent.com/assets/21793/10513417/7d027956-7315-11e5-8eba-e049a1a5c350.png)

Looks like there is a flash-messages initializer in the addon?

**Comment by yankeeinlondon** [comment]
Hmmmm. This should only be in the dev-dependencies (it's used in the demo but not a dependency of the addon per se). I'll have a look at it a soon as I can.

**Comment by yankeeinlondon** [comment]
try npm version `0.2.4` and let me know if this fixes the problem. i think i fixed it but at a client site and can not do full testing right now. :)

**Comment by validkeys** [comment]
hey ken, still getting the same issue. I think it's because you have
ember-cli-flash as a dependency instead of a dev-dependency. Installing
ember-cli-flash in my app resolved the issue,

**Comment by yankeeinlondon** [comment]
yup, should be fixed now: `0.2.7`

**Comment by yankeeinlondon** [comment]
I'll close for now but reopen if you're still having this issue.

**Comment by validkeys** [comment]
awesome. Thanks Ken!
